#ifndef USD_GODOT_VERSION_H
#define USD_GODOT_VERSION_H

#define GODOT_USD_VERSION_MAJOR 0
#define GODOT_USD_VERSION_MINOR 1
#define GODOT_USD_VERSION_PATCH 0

#define GODOT_USD_VERSION_STRING "0.1.0"

#endif // USD_GODOT_VERSION_H
