#ifndef USD_GODOT_VERSION_H
#define USD_GODOT_VERSION_H

#define GODOT_USD_VERSION_MAJOR 0
#define GODOT_USD_VERSION_MINOR 3
#define GODOT_USD_VERSION_PATCH 2

#define GODOT_USD_VERSION_STRING "0.3.2"

#endif // USD_GODOT_VERSION_H
